source 'https://rubygems.org'

gem 'celluloid', '~> 0.16.0'
gem 'contracts'
gem 'exponential-backoff'
gem 'kanban'
gem 'rakuna'
gem 'reel'
gem 'rack'

group 'development' do
  gem 'rspec'
end

ruby '2.2.2'
