---
jenkins:
  base_url: 'http://jenkins.activestate.com/view/Stackato%20components/job/component_image_jobs/job'
  cause: 'WebHook+Triggered'
  secret: JENKINS_AUTH_TOKEN_GOES_HERE
github:
  secret: GITHUB_AUTH_TOKEN_GOES_HERE
repository:
  path: /Users/colstrom/Projects/activestate/stackato-release-st
components:
  src/aok:                 aok-image
  src/appstore:            appstore-image
  src/cloud_controller_ng: cloud_controller_ng-image
  src/console:             console-image
  src/dea_ng:              dea_ng-image
  src/doc:                 doc-image
  src/etcd:                etcd-image
  src/fence:               fence-image
  src/gnatsd:              gnatsd-image
  src/health_manager:      health_manager-image
  src/kato:                kato-image
  src/loggregator:         loggregator-image
  src/logyard-apps-lgr:    logyard_apps_lgr-image
  src/logyard-apps:        logyard_apps-image
  src/logyard:             logyard-image
  src/router:              router-image
  src/services/base:       services__base-image
  src/services/filesystem: services__filesystem-image
  src/services/harbor:     services__harbor-image
  src/services/memcached:  services__memcached-image
  src/services/mongodb:    services__mongodb-image
  src/services/mysql:      services__mysql-image
  src/services/postgresql: services__postgresql-image
  src/services/rabbitmq:   services__rabbitmq-image
  src/services/redis:      services__redis-image
  src/setup-etc:           setup_etc-image
  src/stackato-rest:       stackato_rest-image
  src/stackato-tools:      stackato_tools-image
  src/stackon:             stackon-image
  src/supervisord:         supervisord-image
  src/docker-registry:     docker-registry
  src/docker-base-images/base: docker-base
  src/stackato-app-stacks: stackato-app-stacks
  src/docker-base-images/base-redis: docker-base-redis
  src/docker-base-images/base-mdns: docker-base-mdns
  src/appmdn: appmdns

#TODO: Jenkins job to create
  # src/docker-registry:     docker-registry # (see repo stackato-image-factory)
  # src/stackato-app-stacks: stackato-app-stacks # (see repo stackato-image-factory: stack-alsek)
  # src/packer:              stackato-image-builder
  # src/sentinel:            stackato-image-provisioner

#TODO: Folders to create in stackato-release, move its Sentinel recipes and link it to their jenkins job
# - load_balancer
# - ruby
# - stackato_tty
# - client
# - buildpacks
# - mongodb
# - rabbitmq
# - extra_utilities
# - postgresql
# - redis
# - go
# - nodejs
# - gem_bundler

# Docker images
  # src/docker-base-images/base:            docker-stackato-base
  # src/docker-base-images/base-redis:      docker-base-redis
  # src/docker-base-images/base-go:         docker-base-go
  # src/confdis/server:                     config-redis
  # src/logyard-apps/apptail/redis-server:  applog-redis
  # src/services/base/services-redis:       services-redis
  # src/services/harbor/harbor-redis:       harbor-redis
  # src/appstore/deployer:                  appstore-deployer
  # src/stackato/misc/ephemeral-redis:      ephemeral-redis
  # src/appmdns:                            appmdns

  # What's the role of wscat with logyard: tool for dev
  # activestate/wscat
  # - http://git-mirrors.activestate.com/github.com/ActiveState/logyard-apps.git;applog_endpoint/wscat
  # Already in s-r
  # stackato/appstore:
  # - http://git-mirrors.activestate.com/github.com/ActiveState/appstore.git

  # Maybe outdated since stackato/appmdns is based on stackato/base
  # stackato/base-mdns
  # - http://git-mirrors.activestate.com/github.com/ActiveState/stackato-base-image.git;base-mdns
