source 'https://rubygems.org'

gem 'celluloid', '~> 0.16.0'
gem 'contracts'
gem 'kanban'
gem 'rack'
gem 'rakuna', '~> 1.0'

gem 'reel'

group :development do
  gem 'rspec'
  gem 'typhoeus'
end

ruby '2.2.2'
