---
src/aok:                 aok-image
src/appstore:            appstore
src/cloud_controller_ng: cloud_controller_ng-image
src/console:             console-image
src/dea_ng:              dea_ng-image
src/dea_ng_warden:       dea_ng_warden-image
src/doc:                 doc-image
src/etcd:                etcd-image
src/fence:               fence-image
src/gnatsd:              gnatsd-image
src/health_manager:      health_manager-image
src/kato:                kato-image
src/loggregator:         loggregator-image
src/logyard-apps-lgr:    logyard_apps_lgr-image
src/router:              router-image
src/services/base:       services__base-image
src/services/filesystem: services__filesystem-image
src/services/harbor:     services__harbor-image
src/services/memcached:  services__memcached-image
src/services/mongodb:    services__mongodb-image
src/services/mysql:      services__mysql-image
src/services/postgresql: services__postgresql-image
src/services/rabbitmq:   services__rabbitmq-image
src/services/redis:      services__redis-image
src/setup-etc:           setup_etc-image
src/stackato-rest:       stackato_rest-image
src/stackato-tools:      stackato_tools-image
src/stackon:             stackon-image
src/supervisord:         supervisord-image
src/warden:              warden-image

# Recipes
recipes/aok.rb:                 aok-image
recipes/appstore.rb:            appstore
recipes/cloud_controller_ng.rb: cloud_controller_ng-image
recipes/console.rb:             console-image
recipes/dea_ng.rb:              dea_ng-image
recipes/dea_ng_warden.rb:       dea_ng_warden-image
recipes/doc.rb:                 doc-image
recipes/etcd.rb:                etcd-image
recipes/fence.rb:               fence-image
recipes/gnatsd.rb:              gnatsd-image
recipes/health_manager.rb:      health_manager-image
recipes/kato.rb:                kato-image
recipes/loggregator.rb:         loggregator-image
recipes/logyard-apps-lgr.rb:    logyard_apps_lgr-image
recipes/router.rb:              router-image
recipes/services/base.rb:       services__base-image
recipes/services/filesystem.rb: services__filesystem-image
recipes/services/harbor.rb:     services__harbor-image
recipes/services/memcached.rb:  services__memcached-image
recipes/services/mongodb.rb:    services__mongodb-image
recipes/services/mysql.rb:      services__mysql-image
recipes/services/postgresql.rb: services__postgresql-image
recipes/services/rabbitmq.rb:   services__rabbitmq-image
recipes/services/redis.rb:      services__redis-image
recipes/setup-etc.rb:           setup_etc-image
recipes/stackato-rest.rb:       stackato_rest-image
recipes/stackato-tools.rb:      stackato_tools-image
recipes/stackon.rb:             stackon-image
recipes/supervisord.rb:         supervisord-image
recipes/warden.rb:              warden-image

# Docker images
src/docker-registry:     docker-registry
src/stackato-app-stacks: stackato-app-stacks
src/docker-base-images/base: docker-base
src/docker-base-images/base-redis: docker-base-redis
src/docker-base-images/base-mdns: docker-base-mdns
src/confdis/server: config-redis
src/logyard-apps/apptail/redis-server: applog-redis
src/services/base/services-redis: services-redis
src/services/harbor/harbor-redis: harbor-redis
src/stackato/misc/ephemeral-redis: ephemeral-redis
src/appmdns: appmdns
src/appstore/deployer: appstore-deployer
